from matrix.py import Matrix

if __name__ == "__main__":
    matrix = Matrix((10, 10), list(range(100)))

    print("1. M")
    print(matrix)
    print("\n2. M[1,1]")
    print(matrix[1, 1])
    print("\n3. M[1]")
    print(matrix[1])
    print("\n4. M[-1]")
    print(matrix[-1])
    print("\n5. M[1:4]")
    print(matrix[1:4])
    print("\n6. M[:4]")
    print(matrix[:4])
    print("\n7. M[4:]")
    print(matrix[4:])
    print("\n8. M[:]")
    print(matrix[:])
    print("\n9. M[1:7:2]")
    print(matrix[1:7:2])
    print("\n10. M[:, 1]")
    print(matrix[:, 1])
    print("\n11. M[1:4, 1:4]")
    print(matrix[1:4, 1:4])
    print("\n12. M[1:4, :4]")
    print(matrix[1:4, :4])
    print("\n13. M[1:4, 4:]")
    print(matrix[1:4, 4:])
    print("\n14. M[1:4, :]")
    print(matrix[1:4, :])
    print("\n15. M[-1:]")
    print(matrix[-1:])
    print("\n16. M[-2::-2]")
    print(matrix[-2::-2])
    print("\n17. M[-2::-2,1:4]")
    print(matrix[-2::-2, 1:4])
    print("\n18. M[:, :]")
    print(matrix[:, :])
    print("\n19. M[[1, 4]]")
    print(matrix[[1, 4]])
    print("\n20. M[:, [1,4]]")
    print(matrix[:, [1, 4]])
    print("\n21. M[[1, 4], [1, 4]]")
    print(matrix[[1, 4], [1, 4]])
